#!/bin/bash

if [ "$#" == 0 ]; then
    echo "Error, name required"
    exit 1
fi

for file_name in "$@"; do
    if [ -f "$file_name" ]; then
        read -e -p "Edit file name: " -i "$(basename "$file_name")" new_file_name
        if [ "$new_file_name" ]; then
            mv "$file_name" "$new_file_name"
        fi
    fi
done

exit 0
