#!/bin/bash

if [ "$#" == 0 ]; then
    echo -e "Error, name required"
fi

for file_name in "$@"; do
    if [ -f $file_name ]; then
        echo -ne $file_name'\nNew name: '
        read -e new_file_name
        if [ "$new_file_name" ]; then
            mv "$file_name" "$new_file_name"
        fi
    fi
done

exit 0
