#!/bin/bash

if [[ "$#" < 2 ]]; then
    echo "Error, not enough args"
    exit 1
fi

interval="$1"
shift
command_name="$@"
old="`$command_name`"

while :; do
    new=`$command_name`
    echo "Result:"
    echo $new
    diff="$( diff -u <(echo "$old") <(echo "$new") )"
    if [ "$diff" ]; then
        echo "Unified diff:"
        echo $diff
    fi
    old="$new"
    sleep $interval
done

exit 0
