all: zankonpond.cpp
	g++ -std=c++11 -Wall -Werror -Wextra zankonpond.cpp -o zankonpond

zankonpond: zankonpond.cpp
	g++ -std=c++11 -Wall -Werror -Wextra zankonpond.cpp -o zankonpond

clean:
	rm -f zankonpond
