all: midterm.c midterm2.c
	gcc -g -Wall -Wextra -Werror -o midterm midterm.c 
	gcc -g -Wall -Wextra -Werror -o midterm2 midterm2.c	

midterm: midterm.c
	gcc -g -Wall -Wextra -Werror -o midterm midterm.c

midterm2: midterm2.c
	gcc -g -Wall -Wextra -Werror -o midterm2 midterm2.c

clean:
	rm -f midterm midterm2
