all: midterm.c midterm2.c
	gcc -g -o midterm midterm.c 
	gcc -g -o midterm2 midterm2.c	

midterm: midterm.c
	gcc -g -Wall -o midterm midterm.c

midterm2: midterm2.c
	gcc -g -Wall -o midterm2 midterm2.c

clear:
	rm -f midterm midterm2
